### ISSUE TITLE
Make IRQ wrappers

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#11]
Write the interrupt request line wrappers.

Resources:
- [OSDev Wiki](http://wiki.osdev.org/Interrupts)
- [BrokenThorn](http://www.brokenthorn.com/Resources/OSDev15.html)
- [Bkerndev](http://www.osdever.net/bkerndev/Docs/irqs.htm)
- [Wikipedia](https://en.wikipedia.org/wiki/Interrupt_request_(PC_architecture))

**Comment by davidaylaian** [comment]
Moved to medium priority because #12 is more important.

**Comment by BrandonKoerner** [comment]
I can send this to you tomorrow if you want

**Comment by davidaylaian** [comment]
Closed in 4b22f19e7992fd7e3b1cf12f78de9739dc04361d
