### ISSUE TITLE
Make keyboard driver

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#13]
Write a PS/2 keyboard driver.

Resources:
- [OSDev Wiki](http://wiki.osdev.org/PS2_Keyboard)
- [BrokenThorn](http://www.brokenthorn.com/Resources/OSDev19.html)
- [Bkerndev](http://www.osdever.net/bkerndev/Docs/keyboard.htm)

**Comment by BrandonKoerner** [comment]
it'll be done by tomorrow

**Comment by davidaylaian** [comment]
Made stub in fcb14993b7264abe86b5ebb0e1c85989a4d275f0

**Comment by davidaylaian** [comment]
Closed in 90b060770bf2779d82128a9ad0519b525a6070a6
