### ISSUE TITLE
Make IRQ handlers

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#16]
Write the interrupt request line handlers.

Resources:
- [OSDev Wiki](http://wiki.osdev.org/Interrupts)
- [BrokenThorn](http://www.brokenthorn.com/Resources/OSDev15.html)
- [Bkerndev](http://www.osdever.net/bkerndev/Docs/irqs.htm)
- [Wikipedia](https://en.wikipedia.org/wiki/Interrupt_request_(PC_architecture))

**Comment by BrandonKoerner** [comment]
Workin' on it.
