### ISSUE TITLE
Make PIT driver

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#17]
Write a PIT driver.

Resources:
- [OSDev Wiki](http://wiki.osdev.org/Programmable_Interval_Timer)
- [BrokenThorn](http://www.brokenthorn.com/Resources/OSDev16.html)
- [Bkerndev](http://www.osdever.net/bkerndev/Docs/pit.htm)

**Comment by BrandonKoerner** [comment]
David I'm going to send you code for all of this in the morning for everything: isr stuff, keyboard stuff, irq stuff, PIT stuff, even onboard alarm stuff if you want.

**Comment by C0D3rARCHIE** [comment]
i am going to writen this.

**Comment by C0D3rARCHIE** [comment]
here is a preview of my coders:
`asm_start:`
`	add eax, 01`
`	mov ebx, eax`
`	jmp asm_start`

**Comment by BrandonKoerner** [comment]
I can write one or send you one
Did you see PIT.C and PIT.H?

I also wrote an RTC driver (RTC.C & TIME.H)

**Comment by davidaylaian** [comment]
@ReewassSquared yes I did. Right now I'm still trying to figure out why IRQs aren't working though. I'm opening an issue for it: #19

**Comment by davidaylaian** [comment]
Starting over with issues
