### ISSUE TITLE
Add a case for integers and stuff for the vprintf() method

### ISSUE THREAD

**Issue by BrandonKoerner** [davidaylaian/carbon#18]
I'm sending you an itoa() method that works for unsigned integers tomorrow along with the driver.

The driver i'm gonna send you tomorrow is kinda incomplete and will be completely finished by about monday (July 10th).

**Comment by davidaylaian** [comment]
@ReewassSquared thanks but I already have an iota() that I haven't added to the repo yet.

**Comment by davidaylaian** [comment]
Finished in aaec52dfe4ca89bb03f43d64024a2c116542359f
