### ISSUE TITLE
Make a memory manager

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#21]
Create a memory manager. It should provide the [`malloc`](http://www.tutorialspoint.com/c_standard_library/c_function_malloc.htm), [`calloc`](https://www.tutorialspoint.com/c_standard_library/c_function_calloc.htm), [`realloc`](https://www.tutorialspoint.com/c_standard_library/c_function_realloc.htm), and [`free`](http://www.tutorialspoint.com/c_standard_library/c_function_free.htm) functions.

Memory Management Resources:
- [OSDev Wiki](http://wiki.osdev.org/Category:Memory_management)
- [James Molly](http://www.jamesmolloy.co.uk/tutorial_html/7.-The%20Heap.html)

**Comment by C0D3rARCHIE** [comment]
i will do this now

**Comment by C0D3rARCHIE** [comment]
here is my code!
` void idpaging(uint32_t *first_pte, vaddr from, int size){`
`    from = from & 0xfffff000; // discard bits we don't want`
`    for(;size>0;from+=4096,size-=4096,first_pte++){`
`       *first_pte=from|1;     // mark page present.`
`    }`
` }`

**Comment by davidaylaian** [comment]
Starting over with issues
