### ISSUE TITLE
Programmable Interval Timer (PIT)

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#51]
Write a driver for the [PIT](https://wiki.osdev.org/PIT). It should be part of the HAL, so its files will be located at `kernel/kernel/arch/x86/hal/pit.c`, and (if needed) `kernel/kernel/arch/x86/hal/pit.h`.

- Add to the HAL a function called `get_tick_count` that will be implemented by `pit.c` and prototyped by `hal.h`.

- The PIT driver will also provide a function `pit_install`, which will be called with all of the other installs in `hal_initialize` in `hal.c`.

- If there are any other functions that would be useful for the outside of the HAL to have (maybe `get_timer_rate`?), go ahead and add them!

**Comment by BrandonKoerner** [comment]
using naming convention `get_pit_<value>` (i.e. `get_pit_tick` and `get_pit_rate`) for functions.
