### ISSUE TITLE
Update README.md to include recent structural changes

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#7]
The new [arch](../tree/master/arch) directory is not yet documented in [README.md](../blob/master/README.md).

**Comment by davidaylaian** [comment]
c1e1992e281cd0e44354dae3ffcd00de3ee67655 adds the [kernel/arch](../tree/master/kernel/arch) directory, which should also be listed.

**Comment by davidaylaian** [comment]
Marked as low priority because there might be more structural changes soon.

**Comment by davidaylaian** [comment]
More changes in d35d449177c1246486b83d7b7bf54f006cdbb38f

**Comment by C0D3rARCHIE** [comment]
i will do this now see my pul request

**Comment by davidaylaian** [comment]
Instead, I decided to remove the Organization section from the readme. The docs should contain a fixed version of the Organization somewhere.
