### ISSUE TITLE
Remap PIC

### ISSUE THREAD

**Issue by davidaylaian** [davidaylaian/carbon#9]
Remap the PIC so that...
- IRQs 0-7 are mapped to interrupts 32-39
- IRQs 8-15 are mapped to interrupts 40-47

Resources:
- [OSDev Wiki](http://wiki.osdev.org/PIC)
- [BrokenThorn](http://www.brokenthorn.com/Resources/OSDevPic.html)

**Comment by BrandonKoerner** [comment]
got it.

void irq_remap (void)
{
    outb (0x20, 0x11);
    outb (0xA0, 0x11);
    outb (0x21, 0x20);
    outb (0xA1, 0x28);
    outb (0x21, 0x04);
    outb (0xA1, 0x02);
    outb (0x21, 0x01);
    outb (0xA1, 0x01);
    outb (0x21, 0x0);
    outb (0xA1, 0x0);
}

**Comment by BrandonKoerner** [comment]
um don't you mean irq's 8-15 mapped to 40-47, not 54?

**Comment by davidaylaian** [comment]
@ReewassSquared yes, fixed.
